output: docs
author: gematik GmbH
author_url: https://www.gematik.de
exclude: /*/internal*
github_url: https://github.com/gematik/ehealthinsurance-app-fast-track-ios
theme: fullwidth
swift_build_tool: xcodebuild
documentation:
  - build/docs/generated/*.md
  - doc/*.md
xcodebuild_arguments:
  - "-project"
  - 'GematikKK.xcodeproj'
  - "-scheme"
  - 'GematikKK'
  - '-destination'
  - 'platform=iOS Simulator,name=iPhone 11'
